// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-custom-variable/internal/sdk/models/shared"
	"net/http"
)

type GetCustomVariableRequest struct {
	// Custom vairable ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetCustomVariableRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetCustomVariableResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	CustomVariable *shared.CustomVariable
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetCustomVariableResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetCustomVariableResponse) GetCustomVariable() *shared.CustomVariable {
	if g == nil {
		return nil
	}
	return g.CustomVariable
}

func (g *GetCustomVariableResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetCustomVariableResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
