// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-variable/internal/sdk/models/shared"
	"net/http"
)

type GetCustomVariableRequest struct {
	// Custom vairable ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetCustomVariableRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetCustomVariableResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	CustomVariable *shared.CustomVariable
}

func (o *GetCustomVariableResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetCustomVariableResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetCustomVariableResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetCustomVariableResponse) GetCustomVariable() *shared.CustomVariable {
	if o == nil {
		return nil
	}
	return o.CustomVariable
}
