// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-custom-variable/internal/sdk/models/shared"
	"net/http"
)

type GetVariableContextRequestBody struct {
	Parameters *shared.VariableParameters `json:"parameters,omitempty"`
}

func (g *GetVariableContextRequestBody) GetParameters() *shared.VariableParameters {
	if g == nil {
		return nil
	}
	return g.Parameters
}

type GetVariableContextResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// ok
	VariableContext *shared.VariableContext
}

func (g *GetVariableContextResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetVariableContextResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetVariableContextResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetVariableContextResponse) GetVariableContext() *shared.VariableContext {
	if g == nil {
		return nil
	}
	return g.VariableContext
}
