// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-custom-variable/internal/sdk/models/shared"
	"net/http"
)

type ReplaceTemplatesRequestBody struct {
	Inputs     []string                   `json:"inputs,omitempty"`
	Parameters *shared.VariableParameters `json:"parameters,omitempty"`
}

func (r *ReplaceTemplatesRequestBody) GetInputs() []string {
	if r == nil {
		return nil
	}
	return r.Inputs
}

func (r *ReplaceTemplatesRequestBody) GetParameters() *shared.VariableParameters {
	if r == nil {
		return nil
	}
	return r.Parameters
}

type ReplaceTemplatesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// ok
	ReplacementOutput *shared.ReplacementOutput
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (r *ReplaceTemplatesResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *ReplaceTemplatesResponse) GetReplacementOutput() *shared.ReplacementOutput {
	if r == nil {
		return nil
	}
	return r.ReplacementOutput
}

func (r *ReplaceTemplatesResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *ReplaceTemplatesResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}
