// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-custom-variable/internal/sdk/models/shared"
	"net/http"
)

type ReplaceTemplatesV2RequestBody struct {
	Inputs     []string                   `json:"inputs,omitempty"`
	Parameters *shared.VariableParameters `json:"parameters,omitempty"`
}

func (r *ReplaceTemplatesV2RequestBody) GetInputs() []string {
	if r == nil {
		return nil
	}
	return r.Inputs
}

func (r *ReplaceTemplatesV2RequestBody) GetParameters() *shared.VariableParameters {
	if r == nil {
		return nil
	}
	return r.Parameters
}

type ReplaceTemplatesV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// ok
	ReplacementOutputV2 *shared.ReplacementOutputV2
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (r *ReplaceTemplatesV2Response) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *ReplaceTemplatesV2Response) GetReplacementOutputV2() *shared.ReplacementOutputV2 {
	if r == nil {
		return nil
	}
	return r.ReplacementOutputV2
}

func (r *ReplaceTemplatesV2Response) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *ReplaceTemplatesV2Response) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}
