// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-custom-variable/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-custom-variable/internal/sdk/models/shared"
	"net/http"
)

type SearchVariablesRequestBody struct {
	EntitySchemas []string `json:"entity_schemas,omitempty"`
	From          *int64   `default:"0" json:"from"`
	// 2-letter language code (ISO 639-1)
	Lang *string `default:"de" json:"lang"`
	// Search string
	Query        string              `json:"query"`
	Size         *int64              `default:"25" json:"size"`
	TemplateType shared.TemplateType `json:"template_type"`
}

func (s SearchVariablesRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SearchVariablesRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"query", "template_type"}); err != nil {
		return err
	}
	return nil
}

func (s *SearchVariablesRequestBody) GetEntitySchemas() []string {
	if s == nil {
		return nil
	}
	return s.EntitySchemas
}

func (s *SearchVariablesRequestBody) GetFrom() *int64 {
	if s == nil {
		return nil
	}
	return s.From
}

func (s *SearchVariablesRequestBody) GetLang() *string {
	if s == nil {
		return nil
	}
	return s.Lang
}

func (s *SearchVariablesRequestBody) GetQuery() string {
	if s == nil {
		return ""
	}
	return s.Query
}

func (s *SearchVariablesRequestBody) GetSize() *int64 {
	if s == nil {
		return nil
	}
	return s.Size
}

func (s *SearchVariablesRequestBody) GetTemplateType() shared.TemplateType {
	if s == nil {
		return shared.TemplateType("")
	}
	return s.TemplateType
}

type SearchVariablesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// ok
	Classes []shared.VariableResult
}

func (s *SearchVariablesResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SearchVariablesResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SearchVariablesResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}

func (s *SearchVariablesResponse) GetClasses() []shared.VariableResult {
	if s == nil {
		return nil
	}
	return s.Classes
}
