// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-custom-variable/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-custom-variable/internal/sdk/models/shared"
	"net/http"
)

type SearchVariablesRequestBody struct {
	TemplateType shared.TemplateType `json:"template_type"`
	// Search string
	Query string `json:"query"`
	From  *int64 `default:"0" json:"from"`
	Size  *int64 `default:"25" json:"size"`
	// 2-letter language code (ISO 639-1)
	Lang          *string  `default:"de" json:"lang"`
	EntitySchemas []string `json:"entity_schemas,omitempty"`
}

func (s SearchVariablesRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SearchVariablesRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SearchVariablesRequestBody) GetTemplateType() shared.TemplateType {
	if o == nil {
		return shared.TemplateType("")
	}
	return o.TemplateType
}

func (o *SearchVariablesRequestBody) GetQuery() string {
	if o == nil {
		return ""
	}
	return o.Query
}

func (o *SearchVariablesRequestBody) GetFrom() *int64 {
	if o == nil {
		return nil
	}
	return o.From
}

func (o *SearchVariablesRequestBody) GetSize() *int64 {
	if o == nil {
		return nil
	}
	return o.Size
}

func (o *SearchVariablesRequestBody) GetLang() *string {
	if o == nil {
		return nil
	}
	return o.Lang
}

func (o *SearchVariablesRequestBody) GetEntitySchemas() []string {
	if o == nil {
		return nil
	}
	return o.EntitySchemas
}

type SearchVariablesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// ok
	VariableResults []shared.VariableResult
}

func (o *SearchVariablesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SearchVariablesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SearchVariablesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *SearchVariablesResponse) GetVariableResults() []shared.VariableResult {
	if o == nil {
		return nil
	}
	return o.VariableResults
}
