// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-variable/internal/sdk/models/shared"
	"net/http"
)

// SearchCustomVariablesResponseBody - Success
type SearchCustomVariablesResponseBody struct {
	Results []shared.CustomVariable `json:"results,omitempty"`
	// Total number of results
	Hits *int64 `json:"hits,omitempty"`
}

func (o *SearchCustomVariablesResponseBody) GetResults() []shared.CustomVariable {
	if o == nil {
		return nil
	}
	return o.Results
}

func (o *SearchCustomVariablesResponseBody) GetHits() *int64 {
	if o == nil {
		return nil
	}
	return o.Hits
}

type SearchCustomVariablesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	Object *SearchCustomVariablesResponseBody
}

func (o *SearchCustomVariablesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SearchCustomVariablesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SearchCustomVariablesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *SearchCustomVariablesResponse) GetObject() *SearchCustomVariablesResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
