// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-custom-variable/internal/sdk/models/shared"
	"net/http"
)

// SearchCustomVariablesResponseBody - Success
type SearchCustomVariablesResponseBody struct {
	// Total number of results
	Hits    *int64                  `json:"hits,omitempty"`
	Results []shared.CustomVariable `json:"results,omitempty"`
}

func (s *SearchCustomVariablesResponseBody) GetHits() *int64 {
	if s == nil {
		return nil
	}
	return s.Hits
}

func (s *SearchCustomVariablesResponseBody) GetResults() []shared.CustomVariable {
	if s == nil {
		return nil
	}
	return s.Results
}

type SearchCustomVariablesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	Object *SearchCustomVariablesResponseBody
}

func (s *SearchCustomVariablesResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SearchCustomVariablesResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SearchCustomVariablesResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}

func (s *SearchCustomVariablesResponse) GetObject() *SearchCustomVariablesResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
