// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-custom-variable/internal/sdk/models/shared"
	"net/http"
)

type UpdateCustomVariableRequest struct {
	CustomVariable *shared.CustomVariableInput `request:"mediaType=application/json"`
	// Custom variable ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *UpdateCustomVariableRequest) GetCustomVariable() *shared.CustomVariableInput {
	if o == nil {
		return nil
	}
	return o.CustomVariable
}

func (o *UpdateCustomVariableRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type UpdateCustomVariableResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	CustomVariable *shared.CustomVariable
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *UpdateCustomVariableResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateCustomVariableResponse) GetCustomVariable() *shared.CustomVariable {
	if o == nil {
		return nil
	}
	return o.CustomVariable
}

func (o *UpdateCustomVariableResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateCustomVariableResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
