// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CategoryResult struct {
	Category    *string `json:"category,omitempty"`
	Description *string `json:"description,omitempty"`
}

func (c *CategoryResult) GetCategory() *string {
	if c == nil {
		return nil
	}
	return c.Category
}

func (c *CategoryResult) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}
