// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// Config - Variable configuration
type Config struct {
}

// Type - Custom variable type
type Type string

const (
	TypeOrderTable  Type = "order_table"
	TypeCustom      Type = "custom"
	TypeJourneyLink Type = "journey_link"
	TypeSnippet     Type = "snippet"
)

func (e Type) ToPointer() *Type {
	return &e
}
func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "order_table":
		fallthrough
	case "custom":
		fallthrough
	case "journey_link":
		fallthrough
	case "snippet":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

type CustomVariable struct {
	// The tags of custom variable
	Tags []string `json:"_tags,omitempty"`
	// Variable configuration
	Config *Config `json:"config,omitempty"`
	// Creation time
	CreatedAt *string `json:"created_at,omitempty"`
	// Created by
	CreatedBy *string `json:"created_by,omitempty"`
	// The helper function logic
	HelperLogic *string `json:"helper_logic,omitempty"`
	// The helper function parameter's names
	HelperParams []string `json:"helper_params,omitempty"`
	// ID
	ID *string `json:"id,omitempty"`
	// The key which is used for Handlebar variable syntax {{"{{"}}key}}
	Key string `json:"key"`
	// Custom variable name
	Name *string `json:"name,omitempty"`
	// Handlebar template that used to generate the variable content
	Template string `json:"template"`
	// Custom variable type
	Type *Type `json:"type,omitempty"`
	// Last update time
	UpdatedAt *string `json:"updated_at,omitempty"`
	// Updated by
	UpdatedBy *string `json:"updated_by,omitempty"`
}

func (c *CustomVariable) GetTags() []string {
	if c == nil {
		return nil
	}
	return c.Tags
}

func (c *CustomVariable) GetConfig() *Config {
	if c == nil {
		return nil
	}
	return c.Config
}

func (c *CustomVariable) GetCreatedAt() *string {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *CustomVariable) GetCreatedBy() *string {
	if c == nil {
		return nil
	}
	return c.CreatedBy
}

func (c *CustomVariable) GetHelperLogic() *string {
	if c == nil {
		return nil
	}
	return c.HelperLogic
}

func (c *CustomVariable) GetHelperParams() []string {
	if c == nil {
		return nil
	}
	return c.HelperParams
}

func (c *CustomVariable) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CustomVariable) GetKey() string {
	if c == nil {
		return ""
	}
	return c.Key
}

func (c *CustomVariable) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CustomVariable) GetTemplate() string {
	if c == nil {
		return ""
	}
	return c.Template
}

func (c *CustomVariable) GetType() *Type {
	if c == nil {
		return nil
	}
	return c.Type
}

func (c *CustomVariable) GetUpdatedAt() *string {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

func (c *CustomVariable) GetUpdatedBy() *string {
	if c == nil {
		return nil
	}
	return c.UpdatedBy
}

type CustomVariableInput struct {
	// The tags of custom variable
	Tags []string `json:"_tags,omitempty"`
	// Variable configuration
	Config *Config `json:"config,omitempty"`
	// The helper function logic
	HelperLogic *string `json:"helper_logic,omitempty"`
	// The helper function parameter's names
	HelperParams []string `json:"helper_params,omitempty"`
	// ID
	ID *string `json:"id,omitempty"`
	// The key which is used for Handlebar variable syntax {{"{{"}}key}}
	Key string `json:"key"`
	// Custom variable name
	Name *string `json:"name,omitempty"`
	// Handlebar template that used to generate the variable content
	Template string `json:"template"`
	// Custom variable type
	Type *Type `json:"type,omitempty"`
}

func (c *CustomVariableInput) GetTags() []string {
	if c == nil {
		return nil
	}
	return c.Tags
}

func (c *CustomVariableInput) GetConfig() *Config {
	if c == nil {
		return nil
	}
	return c.Config
}

func (c *CustomVariableInput) GetHelperLogic() *string {
	if c == nil {
		return nil
	}
	return c.HelperLogic
}

func (c *CustomVariableInput) GetHelperParams() []string {
	if c == nil {
		return nil
	}
	return c.HelperParams
}

func (c *CustomVariableInput) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CustomVariableInput) GetKey() string {
	if c == nil {
		return ""
	}
	return c.Key
}

func (c *CustomVariableInput) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CustomVariableInput) GetTemplate() string {
	if c == nil {
		return ""
	}
	return c.Template
}

func (c *CustomVariableInput) GetType() *Type {
	if c == nil {
		return nil
	}
	return c.Type
}
