// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-custom-variable/internal/sdk/internal/utils"
)

// CustomVariablesSearchParamsType - Variable type
type CustomVariablesSearchParamsType string

const (
	CustomVariablesSearchParamsTypeOrderTable  CustomVariablesSearchParamsType = "order_table"
	CustomVariablesSearchParamsTypeCustom      CustomVariablesSearchParamsType = "custom"
	CustomVariablesSearchParamsTypeJourneyLink CustomVariablesSearchParamsType = "journey_link"
)

func (e CustomVariablesSearchParamsType) ToPointer() *CustomVariablesSearchParamsType {
	return &e
}
func (e *CustomVariablesSearchParamsType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "order_table":
		fallthrough
	case "custom":
		fallthrough
	case "journey_link":
		*e = CustomVariablesSearchParamsType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CustomVariablesSearchParamsType: %v", v)
	}
}

type CustomVariablesSearchParams struct {
	// Fields to return
	Fields []string `json:"fields,omitempty"`
	From   *int64   `default:"0" json:"from"`
	// Search string
	Query *string `json:"query,omitempty"`
	Size  *int64  `default:"25" json:"size"`
	// Sort by field
	SortBy *string `json:"sort_by,omitempty"`
	// The tags of custom variable
	Tags []string `json:"tags,omitempty"`
	// Variable type
	Type *CustomVariablesSearchParamsType `json:"type,omitempty"`
}

func (c CustomVariablesSearchParams) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomVariablesSearchParams) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CustomVariablesSearchParams) GetFields() []string {
	if c == nil {
		return nil
	}
	return c.Fields
}

func (c *CustomVariablesSearchParams) GetFrom() *int64 {
	if c == nil {
		return nil
	}
	return c.From
}

func (c *CustomVariablesSearchParams) GetQuery() *string {
	if c == nil {
		return nil
	}
	return c.Query
}

func (c *CustomVariablesSearchParams) GetSize() *int64 {
	if c == nil {
		return nil
	}
	return c.Size
}

func (c *CustomVariablesSearchParams) GetSortBy() *string {
	if c == nil {
		return nil
	}
	return c.SortBy
}

func (c *CustomVariablesSearchParams) GetTags() []string {
	if c == nil {
		return nil
	}
	return c.Tags
}

func (c *CustomVariablesSearchParams) GetType() *CustomVariablesSearchParamsType {
	if c == nil {
		return nil
	}
	return c.Type
}
