// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ExternalCustomVariable struct {
	Value    *string `json:"value,omitempty"`
	Variable *string `json:"variable,omitempty"`
}

func (o *ExternalCustomVariable) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}

func (o *ExternalCustomVariable) GetVariable() *string {
	if o == nil {
		return nil
	}
	return o.Variable
}
