// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ExternalCustomVariable struct {
	Value    *string `json:"value,omitempty"`
	Variable *string `json:"variable,omitempty"`
}

func (e *ExternalCustomVariable) GetValue() *string {
	if e == nil {
		return nil
	}
	return e.Value
}

func (e *ExternalCustomVariable) GetVariable() *string {
	if e == nil {
		return nil
	}
	return e.Variable
}
