// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-custom-variable/internal/sdk/internal/utils"
)

type OutputsType string

const (
	OutputsTypeStr        OutputsType = "str"
	OutputsTypeNumber     OutputsType = "number"
	OutputsTypeBoolean    OutputsType = "boolean"
	OutputsTypeArrayOfAny OutputsType = "arrayOfAny"
	OutputsTypeMapOfAny   OutputsType = "mapOfAny"
)

type Outputs struct {
	Str        *string        `queryParam:"inline,name=outputs"`
	Number     *float64       `queryParam:"inline,name=outputs"`
	Boolean    *bool          `queryParam:"inline,name=outputs"`
	ArrayOfAny []any          `queryParam:"inline,name=outputs"`
	MapOfAny   map[string]any `queryParam:"inline,name=outputs"`

	Type OutputsType
}

func CreateOutputsStr(str string) Outputs {
	typ := OutputsTypeStr

	return Outputs{
		Str:  &str,
		Type: typ,
	}
}

func CreateOutputsNumber(number float64) Outputs {
	typ := OutputsTypeNumber

	return Outputs{
		Number: &number,
		Type:   typ,
	}
}

func CreateOutputsBoolean(boolean bool) Outputs {
	typ := OutputsTypeBoolean

	return Outputs{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateOutputsArrayOfAny(arrayOfAny []any) Outputs {
	typ := OutputsTypeArrayOfAny

	return Outputs{
		ArrayOfAny: arrayOfAny,
		Type:       typ,
	}
}

func CreateOutputsMapOfAny(mapOfAny map[string]any) Outputs {
	typ := OutputsTypeMapOfAny

	return Outputs{
		MapOfAny: mapOfAny,
		Type:     typ,
	}
}

func (u *Outputs) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  OutputsTypeStr,
			Value: &str,
		})
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  OutputsTypeNumber,
			Value: &number,
		})
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  OutputsTypeBoolean,
			Value: &boolean,
		})
	}

	var arrayOfAny []any = []any{}
	if err := utils.UnmarshalJSON(data, &arrayOfAny, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  OutputsTypeArrayOfAny,
			Value: arrayOfAny,
		})
	}

	var mapOfAny map[string]any = map[string]any{}
	if err := utils.UnmarshalJSON(data, &mapOfAny, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  OutputsTypeMapOfAny,
			Value: mapOfAny,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Outputs", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestCandidate(candidates)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Outputs", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(OutputsType)
	switch best.Type {
	case OutputsTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case OutputsTypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	case OutputsTypeBoolean:
		u.Boolean = best.Value.(*bool)
		return nil
	case OutputsTypeArrayOfAny:
		u.ArrayOfAny = best.Value.([]any)
		return nil
	case OutputsTypeMapOfAny:
		u.MapOfAny = best.Value.(map[string]any)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Outputs", string(data))
}

func (u Outputs) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.ArrayOfAny != nil {
		return utils.MarshalJSON(u.ArrayOfAny, "", true)
	}

	if u.MapOfAny != nil {
		return utils.MarshalJSON(u.MapOfAny, "", true)
	}

	return nil, errors.New("could not marshal union type Outputs: all fields are null")
}

type ReplacementOutputV2 struct {
	// Dictionary mapping input templates and variable names to their resolved output values.
	// Values preserve their original types (string, array, object) instead of being stringified.
	//
	// Keys include:
	// - Original input templates (e.g., "Hello {{name}}")
	// - Individual variables found in templates (e.g., "{{name}}", "{{product_images[*].public_url}}")
	//
	Outputs map[string]Outputs `json:"outputs,omitempty"`
}

func (r *ReplacementOutputV2) GetOutputs() map[string]Outputs {
	if r == nil {
		return nil
	}
	return r.Outputs
}
