// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ReplacementOutput struct {
	Outputs []string `json:"outputs,omitempty"`
}

func (r *ReplacementOutput) GetOutputs() []string {
	if r == nil {
		return nil
	}
	return r.Outputs
}
