// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type VariableContext struct {
	Brand          map[string]any `json:"brand,omitempty"`
	Contact        map[string]any `json:"contact,omitempty"`
	Main           map[string]any `json:"main,omitempty"`
	UnsubscribeURL *string        `json:"unsubscribe_url,omitempty"`
}

func (v *VariableContext) GetBrand() map[string]any {
	if v == nil {
		return nil
	}
	return v.Brand
}

func (v *VariableContext) GetContact() map[string]any {
	if v == nil {
		return nil
	}
	return v.Contact
}

func (v *VariableContext) GetMain() map[string]any {
	if v == nil {
		return nil
	}
	return v.Main
}

func (v *VariableContext) GetUnsubscribeURL() *string {
	if v == nil {
		return nil
	}
	return v.UnsubscribeURL
}
