// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-custom-variable/internal/sdk/internal/utils"
)

// ContextData - If context data is available, this data will be used for variable replace.
type ContextData struct {
}

type VariableParameters struct {
	// Brand ID
	BrandID *float64 `json:"brand_id,omitempty"`
	// If context data is available, this data will be used for variable replace.
	ContextData *ContextData `json:"context_data,omitempty"`
	// Custom variables with specified values form other services.
	CustomVariables []ExternalCustomVariable `json:"custom_variables,omitempty"`
	// 2-letter language code (ISO 639-1)
	Language *string `default:"de" json:"language"`
	// The main entity ID. Use main entity in order to use the variable without schema slug prefix - or just pass directly to other object ID.
	MainEntityID *string `json:"main_entity_id,omitempty"`
	// The name of email template
	TemplateName *string `json:"template_name,omitempty"`
	// The tags of email template
	TemplateTags []string     `json:"template_tags,omitempty"`
	TemplateType TemplateType `json:"template_type"`
	// User ID
	UserID *string `json:"user_id,omitempty"`
	// Organization ID of the user
	UserOrgID *string `json:"user_org_id,omitempty"`
	// The version of the variables syntax supported. Default is 1.0
	VariablesVersion *string `json:"variables_version,omitempty"`
}

func (v VariableParameters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VariableParameters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"template_type"}); err != nil {
		return err
	}
	return nil
}

func (v *VariableParameters) GetBrandID() *float64 {
	if v == nil {
		return nil
	}
	return v.BrandID
}

func (v *VariableParameters) GetContextData() *ContextData {
	if v == nil {
		return nil
	}
	return v.ContextData
}

func (v *VariableParameters) GetCustomVariables() []ExternalCustomVariable {
	if v == nil {
		return nil
	}
	return v.CustomVariables
}

func (v *VariableParameters) GetLanguage() *string {
	if v == nil {
		return nil
	}
	return v.Language
}

func (v *VariableParameters) GetMainEntityID() *string {
	if v == nil {
		return nil
	}
	return v.MainEntityID
}

func (v *VariableParameters) GetTemplateName() *string {
	if v == nil {
		return nil
	}
	return v.TemplateName
}

func (v *VariableParameters) GetTemplateTags() []string {
	if v == nil {
		return nil
	}
	return v.TemplateTags
}

func (v *VariableParameters) GetTemplateType() TemplateType {
	if v == nil {
		return TemplateType("")
	}
	return v.TemplateType
}

func (v *VariableParameters) GetUserID() *string {
	if v == nil {
		return nil
	}
	return v.UserID
}

func (v *VariableParameters) GetUserOrgID() *string {
	if v == nil {
		return nil
	}
	return v.UserOrgID
}

func (v *VariableParameters) GetVariablesVersion() *string {
	if v == nil {
		return nil
	}
	return v.VariablesVersion
}
