// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-variable/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-variable/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *CustomVariableResourceModel) ToSharedCustomVariable() *shared.CustomVariable {
	id := new(string)
	if !r.ID.IsUnknown() && !r.ID.IsNull() {
		*id = r.ID.ValueString()
	} else {
		id = nil
	}
	typeVar := new(shared.CustomVariableType)
	if !r.Type.IsUnknown() && !r.Type.IsNull() {
		*typeVar = shared.CustomVariableType(r.Type.ValueString())
	} else {
		typeVar = nil
	}
	name := new(string)
	if !r.Name.IsUnknown() && !r.Name.IsNull() {
		*name = r.Name.ValueString()
	} else {
		name = nil
	}
	key := new(string)
	if !r.Key.IsUnknown() && !r.Key.IsNull() {
		*key = r.Key.ValueString()
	} else {
		key = nil
	}
	var tags []string = []string{}
	for _, tagsItem := range r.Tags {
		tags = append(tags, tagsItem.ValueString())
	}
	var helperParams []string = []string{}
	for _, helperParamsItem := range r.HelperParams {
		helperParams = append(helperParams, helperParamsItem.ValueString())
	}
	helperLogic := new(string)
	if !r.HelperLogic.IsUnknown() && !r.HelperLogic.IsNull() {
		*helperLogic = r.HelperLogic.ValueString()
	} else {
		helperLogic = nil
	}
	var config *shared.Config
	if r.Config != nil {
		config = &shared.Config{}
	}
	template := new(string)
	if !r.Template.IsUnknown() && !r.Template.IsNull() {
		*template = r.Template.ValueString()
	} else {
		template = nil
	}
	createdAt := new(string)
	if !r.CreatedAt.IsUnknown() && !r.CreatedAt.IsNull() {
		*createdAt = r.CreatedAt.ValueString()
	} else {
		createdAt = nil
	}
	createdBy := new(string)
	if !r.CreatedBy.IsUnknown() && !r.CreatedBy.IsNull() {
		*createdBy = r.CreatedBy.ValueString()
	} else {
		createdBy = nil
	}
	updatedAt := new(string)
	if !r.UpdatedAt.IsUnknown() && !r.UpdatedAt.IsNull() {
		*updatedAt = r.UpdatedAt.ValueString()
	} else {
		updatedAt = nil
	}
	updatedBy := new(string)
	if !r.UpdatedBy.IsUnknown() && !r.UpdatedBy.IsNull() {
		*updatedBy = r.UpdatedBy.ValueString()
	} else {
		updatedBy = nil
	}
	out := shared.CustomVariable{
		ID:           id,
		Type:         typeVar,
		Name:         name,
		Key:          key,
		Tags:         tags,
		HelperParams: helperParams,
		HelperLogic:  helperLogic,
		Config:       config,
		Template:     template,
		CreatedAt:    createdAt,
		CreatedBy:    createdBy,
		UpdatedAt:    updatedAt,
		UpdatedBy:    updatedBy,
	}
	return &out
}

func (r *CustomVariableResourceModel) RefreshFromSharedCustomVariable(resp *shared.CustomVariable) {
	if resp != nil {
		r.Tags = []types.String{}
		for _, v := range resp.Tags {
			r.Tags = append(r.Tags, types.StringValue(v))
		}
		if resp.Config == nil {
			r.Config = nil
		} else {
			r.Config = &tfTypes.Config{}
		}
		r.CreatedAt = types.StringPointerValue(resp.CreatedAt)
		r.CreatedBy = types.StringPointerValue(resp.CreatedBy)
		r.HelperLogic = types.StringPointerValue(resp.HelperLogic)
		r.HelperParams = []types.String{}
		for _, v := range resp.HelperParams {
			r.HelperParams = append(r.HelperParams, types.StringValue(v))
		}
		r.ID = types.StringPointerValue(resp.ID)
		r.Key = types.StringPointerValue(resp.Key)
		r.Name = types.StringPointerValue(resp.Name)
		r.Template = types.StringPointerValue(resp.Template)
		if resp.Type != nil {
			r.Type = types.StringValue(string(*resp.Type))
		} else {
			r.Type = types.StringNull()
		}
		r.UpdatedAt = types.StringPointerValue(resp.UpdatedAt)
		r.UpdatedBy = types.StringPointerValue(resp.UpdatedBy)
	}
}
