// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"encoding/json"
	"github.com/epilot-dev/terraform-provider-epilot-custom-variable/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *CustomVariableResourceModel) ToSharedCustomVariableInput() *shared.CustomVariableInput {
	var tags []string = []string{}
	for _, tagsItem := range r.Tags {
		tags = append(tags, tagsItem.ValueString())
	}
	var config interface{}
	if !r.Config.IsUnknown() && !r.Config.IsNull() {
		_ = json.Unmarshal([]byte(r.Config.ValueString()), &config)
	}
	helperLogic := new(string)
	if !r.HelperLogic.IsUnknown() && !r.HelperLogic.IsNull() {
		*helperLogic = r.HelperLogic.ValueString()
	} else {
		helperLogic = nil
	}
	var helperParams []string = []string{}
	for _, helperParamsItem := range r.HelperParams {
		helperParams = append(helperParams, helperParamsItem.ValueString())
	}
	var key string
	key = r.Key.ValueString()

	name := new(string)
	if !r.Name.IsUnknown() && !r.Name.IsNull() {
		*name = r.Name.ValueString()
	} else {
		name = nil
	}
	var template string
	template = r.Template.ValueString()

	typeVar := new(shared.Type)
	if !r.Type.IsUnknown() && !r.Type.IsNull() {
		*typeVar = shared.Type(r.Type.ValueString())
	} else {
		typeVar = nil
	}
	out := shared.CustomVariableInput{
		Tags:         tags,
		Config:       config,
		HelperLogic:  helperLogic,
		HelperParams: helperParams,
		Key:          key,
		Name:         name,
		Template:     template,
		Type:         typeVar,
	}
	return &out
}

func (r *CustomVariableResourceModel) RefreshFromSharedCustomVariable(resp *shared.CustomVariable) {
	if resp != nil {
		r.Tags = []types.String{}
		for _, v := range resp.Tags {
			r.Tags = append(r.Tags, types.StringValue(v))
		}
		if resp.Config == nil {
			r.Config = types.StringNull()
		} else {
			configResult, _ := json.Marshal(resp.Config)
			r.Config = types.StringValue(string(configResult))
		}
		r.CreatedAt = types.StringPointerValue(resp.CreatedAt)
		r.CreatedBy = types.StringPointerValue(resp.CreatedBy)
		r.HelperLogic = types.StringPointerValue(resp.HelperLogic)
		r.HelperParams = []types.String{}
		for _, v := range resp.HelperParams {
			r.HelperParams = append(r.HelperParams, types.StringValue(v))
		}
		r.ID = types.StringPointerValue(resp.ID)
		r.Key = types.StringValue(resp.Key)
		r.Name = types.StringPointerValue(resp.Name)
		r.Template = types.StringValue(resp.Template)
		if resp.Type != nil {
			r.Type = types.StringValue(string(*resp.Type))
		} else {
			r.Type = types.StringNull()
		}
		r.UpdatedAt = types.StringPointerValue(resp.UpdatedAt)
		r.UpdatedBy = types.StringPointerValue(resp.UpdatedBy)
	}
}
