// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/epilot-dev/terraform-provider-epilot-custom-variable/internal/sdk"
	"github.com/epilot-dev/terraform-provider-epilot-custom-variable/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/action"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/ephemeral"
	"github.com/hashicorp/terraform-plugin-framework/function"
	"github.com/hashicorp/terraform-plugin-framework/list"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"net/http"
)

var _ provider.Provider = (*EpilotCustomVariableProvider)(nil)
var _ provider.ProviderWithActions = (*EpilotCustomVariableProvider)(nil)
var _ provider.ProviderWithEphemeralResources = (*EpilotCustomVariableProvider)(nil)
var _ provider.ProviderWithFunctions = (*EpilotCustomVariableProvider)(nil)

type EpilotCustomVariableProvider struct {
	// version is set to the provider version on release, "dev" when the
	// provider is built and ran locally, and "test" when running acceptance
	// testing.
	version string
}

// EpilotCustomVariableProviderModel describes the provider data model.
type EpilotCustomVariableProviderModel struct {
	EpilotAuth types.String `tfsdk:"epilot_auth"`
	EpilotOrg  types.String `tfsdk:"epilot_org"`
	ServerURL  types.String `tfsdk:"server_url"`
}

func (p *EpilotCustomVariableProvider) Metadata(ctx context.Context, req provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "epilot-custom-variable"
	resp.Version = p.version
}

func (p *EpilotCustomVariableProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"epilot_auth": schema.StringAttribute{
				MarkdownDescription: `Authorization header with epilot OAuth2 bearer token.`,
				Optional:            true,
				Sensitive:           true,
			},
			"epilot_org": schema.StringAttribute{
				MarkdownDescription: `Overrides the target organization.`,
				Optional:            true,
				Sensitive:           true,
			},
			"server_url": schema.StringAttribute{
				Description: `Server URL (defaults to https://template-variables-api.sls.epilot.io)`,
				Optional:    true,
			},
		},
		MarkdownDescription: `Template Variables API: This API provides dynamic template processing and variable management, seamless Handlebars template compilation, custom variable operations, and context-aware content generation across email, document templates and snippets.`,
	}
}

func (p *EpilotCustomVariableProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data EpilotCustomVariableProviderModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	serverUrl := data.ServerURL.ValueString()

	if serverUrl == "" {
		serverUrl = "https://template-variables-api.sls.epilot.io"
	}

	security := shared.Security{}

	if !data.EpilotAuth.IsUnknown() {
		security.EpilotAuth = data.EpilotAuth.ValueStringPointer()
	}

	if !data.EpilotOrg.IsUnknown() {
		security.EpilotOrg = data.EpilotOrg.ValueStringPointer()
	}

	providerHTTPTransportOpts := ProviderHTTPTransportOpts{
		SetHeaders: make(map[string]string),
		Transport:  http.DefaultTransport,
	}

	httpClient := http.DefaultClient
	httpClient.Transport = NewProviderHTTPTransport(providerHTTPTransportOpts)

	opts := []sdk.SDKOption{
		sdk.WithServerURL(serverUrl),
		sdk.WithSecurity(security),
		sdk.WithClient(httpClient),
	}

	client := sdk.New(opts...)
	resp.ActionData = client
	resp.DataSourceData = client
	resp.EphemeralResourceData = client
	resp.ListResourceData = client
	resp.ResourceData = client
}

func (p *EpilotCustomVariableProvider) Functions(_ context.Context) []func() function.Function {
	return []func() function.Function{}
}

func (p *EpilotCustomVariableProvider) Actions(_ context.Context) []func() action.Action {
	return []func() action.Action{}
}

func (p *EpilotCustomVariableProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewCustomVariableResource,
	}
}

func (p *EpilotCustomVariableProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewCustomVariableDataSource,
	}
}

func (p *EpilotCustomVariableProvider) EphemeralResources(ctx context.Context) []func() ephemeral.EphemeralResource {
	return []func() ephemeral.EphemeralResource{}
}

func (p *EpilotCustomVariableProvider) ListResources(ctx context.Context) []func() list.ListResource {
	return []func() list.ListResource{}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &EpilotCustomVariableProvider{
			version: version,
		}
	}
}
